samples:
    SRR7537362: 
        R1 : "data/samples/SRR7537362_R1.fastq.gz"
        R2 : "data/samples/SRR7537362_R2.fastq.gz"
fn_gtf : "data/gencode.v48.primary_assembly.annotation.gtf"
fa_in : 'data/GRCh38.primary_assembly.genome.fa'
BWA-MEM2IDX : "data/GRCh38.primary_assembly.genome.bowtie2_index/GRCh38.primary_assembly.genome"
home : "/mnt/liuq/test/singularity"
container : "dnaseseq.sif"
all_motifs : "motifs/all_motifs.txt"
species : "hsa"